spring.application.name=configserver
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.client.service-url.defaultZone=http://localhost:8666/eureka/

server.port=7004


# =========================================================
# GIT CONFIGURATION
# =========================================================

spring.cloud.config.server.git.uri=https://github.com/Amish-03/democonfig1.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true

spring.cloud.config.server.git.username=Amish-03
spring.cloud.config.server.git.password=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
