pipeline {
    agent any
C:\ProgramData\Jenkins\.jenkins\workspace\LoginServiceTesting
    stages {

        stage('Checkout') {
            steps {
                checkout dev
            }
        }

        stage('Compile') {
            steps {
                bat '''
                cd C:\ProgramData\Jenkins\.jenkins\workspace\LoginServiceTesting\configserver
                mvn clean compile'''
            }
        }

        stage('Test') {
            steps {
                bat '''
                cd C:\ProgramData\Jenkins\.jenkins\workspace\LoginServiceTesting\configserver
                mvn test'''
            }
        }

        stage('Package') {
            steps {
                bat '''
                cd C:\ProgramData\Jenkins\.jenkins\workspace\LoginServiceTesting\configserver
                mvn package -DskipTests'''
            }
        }
    }

    post {
        success {
            echo 'Build, tests and packaging completed successfully!'
        }

        failure {
            echo 'Pipeline failed.'
        }
    }
}